import * as THREE from 'three';
import { BlockShape, createFullCubeShape, createShapeFromBoxes } from './BlockShape';

export interface BlockDef {
  id: number;
  name: string;
  color: THREE.Color;
  breakable: boolean;
  transparent: boolean; // 半透明ブロック（Glass, Leaves など）
  shape?: BlockShape;   // カスタム形状（省略時はフルキューブ）
}

// ブロック定義
const defs: BlockDef[] = [
  // 基本ブロック
  { id: 1, name: 'Grass', color: new THREE.Color(0x5da84c), breakable: true, transparent: false },
  { id: 2, name: 'Dirt', color: new THREE.Color(0x8b6914), breakable: true, transparent: false },
  { id: 3, name: 'Stone', color: new THREE.Color(0x888888), breakable: true, transparent: false },
  { id: 4, name: 'Wood', color: new THREE.Color(0xa0722a), breakable: true, transparent: false },
  { id: 5, name: 'Sand', color: new THREE.Color(0xdbc67b), breakable: true, transparent: false },
  { id: 6, name: 'Water', color: new THREE.Color(0x3399ff), breakable: false, transparent: true },
  // 自然物系
  { id: 7, name: 'Oak Log', color: new THREE.Color(0x6b4226), breakable: true, transparent: false },
  { id: 8, name: 'Leaves', color: new THREE.Color(0x2d8a2d), breakable: true, transparent: true },
  { id: 9, name: 'Flower', color: new THREE.Color(0x5da84c), breakable: true, transparent: false },
  { id: 10, name: 'Snow', color: new THREE.Color(0xf0f0f0), breakable: true, transparent: false },
  { id: 11, name: 'Ice', color: new THREE.Color(0xa0d8ef), breakable: true, transparent: false },
  // 建物系
  { id: 12, name: 'Brick', color: new THREE.Color(0xb5503c), breakable: true, transparent: false },
  { id: 13, name: 'Stone Brick', color: new THREE.Color(0x999999), breakable: true, transparent: false },
  { id: 14, name: 'Glass', color: new THREE.Color(0xc8e8f0), breakable: true, transparent: true },
  { id: 15, name: 'Planks', color: new THREE.Color(0xc49a4a), breakable: true, transparent: false },
  { id: 16, name: 'Wool White', color: new THREE.Color(0xf0f0f0), breakable: true, transparent: false },
  { id: 17, name: 'Wool Red', color: new THREE.Color(0xcc3333), breakable: true, transparent: false },
  { id: 18, name: 'Wool Blue', color: new THREE.Color(0x3355cc), breakable: true, transparent: false },
  // 自然物系（追加）
  { id: 19, name: 'Cobblestone', color: new THREE.Color(0x777777), breakable: true, transparent: false },
  { id: 20, name: 'Clay', color: new THREE.Color(0xb0a090), breakable: true, transparent: false },
  { id: 21, name: 'Gravel', color: new THREE.Color(0x888070), breakable: true, transparent: false },
  { id: 22, name: 'Sandstone', color: new THREE.Color(0xd4b96a), breakable: true, transparent: false },
  { id: 23, name: 'Cactus', color: new THREE.Color(0x2d7a2d), breakable: true, transparent: false },
  { id: 24, name: 'Mushroom', color: new THREE.Color(0x8b4513), breakable: true, transparent: false },
  { id: 25, name: 'Pumpkin', color: new THREE.Color(0xe88020), breakable: true, transparent: false },
  // 建築材系（追加）
  { id: 26, name: 'Concrete', color: new THREE.Color(0xcccccc), breakable: true, transparent: false },
  { id: 27, name: 'Tile', color: new THREE.Color(0xe0d0b0), breakable: true, transparent: false },
  { id: 28, name: 'Iron', color: new THREE.Color(0xc8c8d0), breakable: true, transparent: false },
  { id: 29, name: 'Wool Yellow', color: new THREE.Color(0xddcc33), breakable: true, transparent: false },
  { id: 30, name: 'Wool Green', color: new THREE.Color(0x33aa33), breakable: true, transparent: false },
  { id: 31, name: 'Wool Orange', color: new THREE.Color(0xdd8833), breakable: true, transparent: false },
  { id: 32, name: 'Wool Black', color: new THREE.Color(0x222222), breakable: true, transparent: false },
  { id: 33, name: 'Bookshelf', color: new THREE.Color(0x8b6914), breakable: true, transparent: false },
  // 光源
  { id: 34, name: 'Torch', color: new THREE.Color(0xff8c00), breakable: true, transparent: true,
    shape: createShapeFromBoxes([{ min: [7, 0, 7], max: [9, 10, 9] }]) },

  // 自然物系（拡張）
  { id: 35, name: 'Birch Log',      color: new THREE.Color(0xd4c89a), breakable: true, transparent: false },
  { id: 36, name: 'Jungle Log',     color: new THREE.Color(0x5a3e1b), breakable: true, transparent: false },
  { id: 37, name: 'Dark Oak Log',   color: new THREE.Color(0x2e1f0e), breakable: true, transparent: false },
  { id: 38, name: 'Birch Leaves',   color: new THREE.Color(0x7fb87f), breakable: true, transparent: true  },
  { id: 39, name: 'Jungle Leaves',  color: new THREE.Color(0x1a7a1a), breakable: true, transparent: true  },
  { id: 40, name: 'Moss Stone',     color: new THREE.Color(0x5a7a4a), breakable: true, transparent: false },
  { id: 41, name: 'Mud',            color: new THREE.Color(0x6b5040), breakable: true, transparent: false },
  { id: 42, name: 'Mycelium',       color: new THREE.Color(0x7a6070), breakable: true, transparent: false },
  { id: 43, name: 'Nether Rack',    color: new THREE.Color(0x7a2020), breakable: true, transparent: false },
  { id: 44, name: 'Soul Sand',      color: new THREE.Color(0x5a4a38), breakable: true, transparent: false },
  { id: 45, name: 'Basalt',         color: new THREE.Color(0x4a4a50), breakable: true, transparent: false },
  { id: 46, name: 'Magma',          color: new THREE.Color(0xcc5500), breakable: true, transparent: false },
  { id: 47, name: 'Coral Red',      color: new THREE.Color(0xdd4444), breakable: true, transparent: true  },
  { id: 48, name: 'Coral Blue',     color: new THREE.Color(0x4466dd), breakable: true, transparent: true  },
  { id: 49, name: 'Sponge',         color: new THREE.Color(0xc8b800), breakable: true, transparent: false },
  { id: 50, name: 'Granite',        color: new THREE.Color(0xc07060), breakable: true, transparent: false },
  { id: 51, name: 'Andesite',       color: new THREE.Color(0x909090), breakable: true, transparent: false },
  { id: 52, name: 'Diorite',        color: new THREE.Color(0xd0d0d0), breakable: true, transparent: false },
  { id: 53, name: 'Bedrock',        color: new THREE.Color(0x333340), breakable: true, transparent: false },
  { id: 54, name: 'Coal Ore',       color: new THREE.Color(0x555555), breakable: true, transparent: false },
  { id: 55, name: 'Iron Ore',       color: new THREE.Color(0x9a7a6a), breakable: true, transparent: false },
  { id: 56, name: 'Gold Ore',       color: new THREE.Color(0xd4a820), breakable: true, transparent: false },
  { id: 57, name: 'Diamond Ore',    color: new THREE.Color(0x50c8d0), breakable: true, transparent: false },
  { id: 58, name: 'Emerald Ore',    color: new THREE.Color(0x30c060), breakable: true, transparent: false },

  // 建築材系（拡張）
  { id: 59, name: 'Mossy Stone Brick',  color: new THREE.Color(0x6a8a5a), breakable: true, transparent: false },
  { id: 60, name: 'Cracked Stone Brick',color: new THREE.Color(0x777777), breakable: true, transparent: false },
  { id: 61, name: 'Chiseled Stone',     color: new THREE.Color(0xaaaaaa), breakable: true, transparent: false },
  { id: 62, name: 'Smooth Stone',       color: new THREE.Color(0xbbbbbb), breakable: true, transparent: false },
  { id: 63, name: 'Cut Sandstone',      color: new THREE.Color(0xd8c870), breakable: true, transparent: false },
  { id: 64, name: 'Red Sandstone',      color: new THREE.Color(0xb86030), breakable: true, transparent: false },
  { id: 65, name: 'Nether Brick',       color: new THREE.Color(0x3a1a1a), breakable: true, transparent: false },
  { id: 66, name: 'Red Nether Brick',   color: new THREE.Color(0x6a1010), breakable: true, transparent: false },
  { id: 67, name: 'Purpur Block',       color: new THREE.Color(0x996699), breakable: true, transparent: false },
  { id: 68, name: 'End Stone',          color: new THREE.Color(0xd8d890), breakable: true, transparent: false },
  { id: 69, name: 'Obsidian',           color: new THREE.Color(0x1a0a2a), breakable: true, transparent: false },
  { id: 70, name: 'Quartz',             color: new THREE.Color(0xf0ece4), breakable: true, transparent: false },
  { id: 71, name: 'Smooth Quartz',      color: new THREE.Color(0xf4f0e8), breakable: true, transparent: false },
  { id: 72, name: 'Gold Block',         color: new THREE.Color(0xf0c020), breakable: true, transparent: false },
  { id: 73, name: 'Diamond Block',      color: new THREE.Color(0x60d8e0), breakable: true, transparent: false },
  { id: 74, name: 'Emerald Block',      color: new THREE.Color(0x20c050), breakable: true, transparent: false },
  { id: 75, name: 'Lapis Block',        color: new THREE.Color(0x2244aa), breakable: true, transparent: false },
  { id: 76, name: 'Coal Block',         color: new THREE.Color(0x222222), breakable: true, transparent: false },
  { id: 77, name: 'Copper Block',       color: new THREE.Color(0xc07848), breakable: true, transparent: false },
  { id: 78, name: 'Waxed Copper',       color: new THREE.Color(0xd89060), breakable: true, transparent: false },
  { id: 79, name: 'Amethyst Block',     color: new THREE.Color(0x9966cc), breakable: true, transparent: false },
  { id: 80, name: 'Deepslate',          color: new THREE.Color(0x444450), breakable: true, transparent: false },
  { id: 81, name: 'Smooth Basalt',      color: new THREE.Color(0x383840), breakable: true, transparent: false },
  { id: 82, name: 'Tuff',              color: new THREE.Color(0x7a7a70), breakable: true, transparent: false },
  { id: 83, name: 'Calcite',            color: new THREE.Color(0xeeeee8), breakable: true, transparent: false },
  { id: 84, name: 'Dripstone',          color: new THREE.Color(0x9a8870), breakable: true, transparent: false },
  { id: 85, name: 'Mud Brick',          color: new THREE.Color(0x9a7a5a), breakable: true, transparent: false },

  // 装飾系（拡張）
  { id: 86,  name: 'Wool Purple',               color: new THREE.Color(0x882299), breakable: true, transparent: false },
  { id: 87,  name: 'Wool Cyan',                 color: new THREE.Color(0x229988), breakable: true, transparent: false },
  { id: 88,  name: 'Wool Lime',                 color: new THREE.Color(0x66cc33), breakable: true, transparent: false },
  { id: 89,  name: 'Wool Pink',                 color: new THREE.Color(0xee8899), breakable: true, transparent: false },
  { id: 90,  name: 'Wool Magenta',              color: new THREE.Color(0xcc44aa), breakable: true, transparent: false },
  { id: 91,  name: 'Wool Brown',                color: new THREE.Color(0x7a5030), breakable: true, transparent: false },
  { id: 92,  name: 'Wool Gray',                 color: new THREE.Color(0x777788), breakable: true, transparent: false },
  { id: 93,  name: 'Wool Light Blue',           color: new THREE.Color(0x6699ee), breakable: true, transparent: false },
  { id: 94,  name: 'Glazed Terracotta Red',     color: new THREE.Color(0xaa4433), breakable: true, transparent: false },
  { id: 95,  name: 'Glazed Terracotta Blue',    color: new THREE.Color(0x334488), breakable: true, transparent: false },
  { id: 96,  name: 'Glazed Terracotta Yellow',  color: new THREE.Color(0xccaa22), breakable: true, transparent: false },
  { id: 97,  name: 'Glazed Terracotta Green',   color: new THREE.Color(0x336633), breakable: true, transparent: false },
  { id: 98,  name: 'Glazed Terracotta White',   color: new THREE.Color(0xddddcc), breakable: true, transparent: false },
  { id: 99,  name: 'Lantern',                   color: new THREE.Color(0xffcc44), breakable: true, transparent: true  },
  { id: 100, name: 'Glowstone',                 color: new THREE.Color(0xffd080), breakable: true, transparent: false },
  { id: 101, name: 'Sea Lantern',               color: new THREE.Color(0xaaeedd), breakable: true, transparent: true  },
  { id: 102, name: 'Shroomlight',               color: new THREE.Color(0xff9933), breakable: true, transparent: false },
];

const byId = new Map<number, BlockDef>();
for (const d of defs) byId.set(d.id, d);

export const BlockTypes = {
  AIR: 0,
  GRASS: 1,
  DIRT: 2,
  STONE: 3,
  WOOD: 4,
  SAND: 5,
  WATER: 6,
  OAK_LOG: 7,
  LEAVES: 8,
  FLOWER: 9,
  SNOW: 10,
  ICE: 11,
  BRICK: 12,
  STONE_BRICK: 13,
  GLASS: 14,
  PLANKS: 15,
  WOOL_WHITE: 16,
  WOOL_RED: 17,
  WOOL_BLUE: 18,
  COBBLESTONE: 19,
  CLAY: 20,
  GRAVEL: 21,
  SANDSTONE: 22,
  CACTUS: 23,
  MUSHROOM: 24,
  PUMPKIN: 25,
  CONCRETE: 26,
  TILE: 27,
  IRON: 28,
  WOOL_YELLOW: 29,
  WOOL_GREEN: 30,
  WOOL_ORANGE: 31,
  WOOL_BLACK: 32,
  BOOKSHELF: 33,
  TORCH: 34,
  // 自然物系（拡張）
  BIRCH_LOG: 35,
  JUNGLE_LOG: 36,
  DARK_OAK_LOG: 37,
  BIRCH_LEAVES: 38,
  JUNGLE_LEAVES: 39,
  MOSS_STONE: 40,
  MUD: 41,
  MYCELIUM: 42,
  NETHER_RACK: 43,
  SOUL_SAND: 44,
  BASALT: 45,
  MAGMA: 46,
  CORAL_RED: 47,
  CORAL_BLUE: 48,
  SPONGE: 49,
  GRANITE: 50,
  ANDESITE: 51,
  DIORITE: 52,
  BEDROCK: 53,
  COAL_ORE: 54,
  IRON_ORE: 55,
  GOLD_ORE: 56,
  DIAMOND_ORE: 57,
  EMERALD_ORE: 58,
  // 建築材系（拡張）
  MOSSY_STONE_BRICK: 59,
  CRACKED_STONE_BRICK: 60,
  CHISELED_STONE: 61,
  SMOOTH_STONE: 62,
  CUT_SANDSTONE: 63,
  RED_SANDSTONE: 64,
  NETHER_BRICK: 65,
  RED_NETHER_BRICK: 66,
  PURPUR_BLOCK: 67,
  END_STONE: 68,
  OBSIDIAN: 69,
  QUARTZ: 70,
  SMOOTH_QUARTZ: 71,
  GOLD_BLOCK: 72,
  DIAMOND_BLOCK: 73,
  EMERALD_BLOCK: 74,
  LAPIS_BLOCK: 75,
  COAL_BLOCK: 76,
  COPPER_BLOCK: 77,
  WAXED_COPPER: 78,
  AMETHYST_BLOCK: 79,
  DEEPSLATE: 80,
  SMOOTH_BASALT: 81,
  TUFF: 82,
  CALCITE: 83,
  DRIPSTONE: 84,
  MUD_BRICK: 85,
  // 装飾系（拡張）
  WOOL_PURPLE: 86,
  WOOL_CYAN: 87,
  WOOL_LIME: 88,
  WOOL_PINK: 89,
  WOOL_MAGENTA: 90,
  WOOL_BROWN: 91,
  WOOL_GRAY: 92,
  WOOL_LIGHT_BLUE: 93,
  GLAZED_TERRACOTTA_RED: 94,
  GLAZED_TERRACOTTA_BLUE: 95,
  GLAZED_TERRACOTTA_YELLOW: 96,
  GLAZED_TERRACOTTA_GREEN: 97,
  GLAZED_TERRACOTTA_WHITE: 98,
  LANTERN: 99,
  GLOWSTONE: 100,
  SEA_LANTERN: 101,
  SHROOMLIGHT: 102,
  get(id: number): BlockDef | undefined {
    return byId.get(id);
  },
  all(): readonly BlockDef[] {
    return defs;
  },
  isTransparent(id: number): boolean {
    if (id === 0) return true; // AIR
    const def = byId.get(id);
    return def ? def.transparent : false;
  },
  getShape(id: number): BlockShape {
    const def = byId.get(id);
    return def?.shape ?? createFullCubeShape();
  },
  isFullCube(id: number): boolean {
    if (id === 0) return false;
    const def = byId.get(id);
    return def?.shape ? def.shape.isFullCube : true;
  },
} as const;
